### ISSUE TITLE
Unable to open from Browser

### ISSUE THREAD

**Issue by bb14521** [BIMscript/docker-bimserver#1]
Hi
 i am done with installing in my machine (digital ocean droplet)
now i want to check or use in browser.  i enter the the URL browser serverAdd/8080/BIMserver
but  does not open anything. 
I did same in my another server,  its working fine.

**Comment by px3l** [comment]
Hi there, yes I have noticed it has started to do this. I'm not sure why yet. When you say it is working fine in your other server, what do you mean? Can you explain when it worked and when it didn't?

**Comment by bb14521** [comment]
Its working fine here http://lab.gdy.club:8080/BIMserver  

 i have installed with this tutorial https://bhushanbharat.wordpress.com/2015/10/13/install-bimserver-on-ubuntu-14-04/

**Comment by px3l** [comment]
Ok so after some bug checking it is deploying the application inside Tomcat but it is not starting the service. Logs are suggesting it is a corrupted .war file. Are you using the latest release of BIMserver (2015-11-04) on your working server?

**Comment by px3l** [comment]
This is the error I am getting (see below) from
```
/logs/catalina.2015-11-30.log 
```
There are no logs inside the BIMserver webapps folder. I can currently only guess it is a config issue in one of the xml files. However I have created this Dockerfile from the same updated instructions from  bimserver github and it was working perfectly until the other day... are you getting any logs inside 
```
opt/tomcat/webapps/BIMserver/WEB-INF/logs
```
?

```
30-Nov-2015 12:05:30.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.28
30-Nov-2015 12:05:30.035 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 7 2015 18:25:21 UTC
30-Nov-2015 12:05:30.036 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.28.0
30-Nov-2015 12:05:30.036 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
30-Nov-2015 12:05:30.036 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.13.0-68-generic
30-Nov-2015 12:05:30.036 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
30-Nov-2015 12:05:30.037 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-7-openjdk-amd64/jre
30-Nov-2015 12:05:30.037 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_91-b02
30-Nov-2015 12:05:30.037 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
30-Nov-2015 12:05:30.037 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
30-Nov-2015 12:05:30.038 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
30-Nov-2015 12:05:30.038 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
30-Nov-2015 12:05:30.039 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
30-Nov-2015 12:05:30.039 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
30-Nov-2015 12:05:30.039 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
30-Nov-2015 12:05:30.039 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
30-Nov-2015 12:05:30.040 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
30-Nov-2015 12:05:30.040 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
30-Nov-2015 12:05:30.040 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/opt/tomcat/endorsed
30-Nov-2015 12:05:30.040 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
30-Nov-2015 12:05:30.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
30-Nov-2015 12:05:30.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
30-Nov-2015 12:05:30.041 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
30-Nov-2015 12:05:30.194 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
30-Nov-2015 12:05:30.222 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
30-Nov-2015 12:05:30.226 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
30-Nov-2015 12:05:30.231 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
30-Nov-2015 12:05:30.242 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 820 ms
30-Nov-2015 12:05:30.302 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
30-Nov-2015 12:05:30.306 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.28
30-Nov-2015 12:05:30.366 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /opt/tomcat/webapps/BIMserver.war
30-Nov-2015 12:05:30.388 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
30-Nov-2015 12:05:30.388 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'attiResourceLocking' to 'true' did not find a matching property.
30-Nov-2015 12:05:42.829 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
30-Nov-2015 12:05:42.835 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
30-Nov-2015 12:05:42.846 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/BIMserver] startup failed due to previous errors
30-Nov-2015 12:05:42.908 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /opt/tomcat/webapps/BIMserver.war has finished in 12,541 ms
30-Nov-2015 12:05:42.934 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/manager
30-Nov-2015 12:05:43.063 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/manager has finished in 129 ms
30-Nov-2015 12:05:43.066 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/host-manager
30-Nov-2015 12:05:43.126 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/host-manager has finished in 59 ms
30-Nov-2015 12:05:43.126 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/docs
30-Nov-2015 12:05:43.151 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/docs has finished in 25 ms
30-Nov-2015 12:05:43.152 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/examples
30-Nov-2015 12:05:43.700 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/examples has finished in 548 ms
30-Nov-2015 12:05:43.701 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /opt/tomcat/webapps/ROOT
30-Nov-2015 12:05:43.723 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /opt/tomcat/webapps/ROOT has finished in 23 ms
30-Nov-2015 12:05:43.731 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
30-Nov-2015 12:05:43.738 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
30-Nov-2015 12:05:43.746 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 13503 ms
```

**Comment by bb14521** [comment]
Get a signature like this: Click here!

On Mon, Nov 30, 2015 at 4:51 PM, px3l notifications@github.com wrote:

> Ok so after some bug checking it is deploying the application inside Tomcat but it is not starting the service. Logs are suggesting it is a corrupted .war file. Are you using the latest release of BIMserver (2015-11-04) on your working server?

No, its BIMserver 1.4
ROOT.war f link is not working. i think this the problem with ROOT.war file.

---

Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by px3l** [comment]
UPDATE - Tomcat 8.0.30 is successfully installing with set username and password. It is successfully wget 'ing the latest .war file release of the BIMserver and autodeploying as per config. The BIMserver service is then not starting. Upon going to Tomcat manager, we cannot manually start the service as it throws an error `FAIL - Application at context path /BIMserver could not be started`

From catalina log:

``` ...
05-Jan-2016 11:30:58.047 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
05-Jan-2016 11:30:58.051 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 11752 ms
05-Jan-2016 11:33:02.276 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
05-Jan-2016 11:33:02.277 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.startInternal Context [/BIMserver] startup failed due to previous errors
...
```

From manager log:

``` ...
05-Jan-2016 11:30:58.047 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
05-Jan-2016 11:30:58.051 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 11752 ms
05-Jan-2016 11:33:02.276 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
05-Jan-2016 11:33:02.277 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.startInternal Context [/BIMserver] startup failed due to previous errors
...
```

From localhost log:

``` ...
05-Jan-2016 11:30:58.007 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
05-Jan-2016 11:30:58.007 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
05-Jan-2016 11:33:02.275 INFO [http-nio-8080-exec-5] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
05-Jan-2016 11:33:02.275 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class org.bimserver.web.WarServerInitializer
 java.lang.UnsupportedClassVersionError: org/bimserver/web/WarServerInitializer : Unsupported major.minor version 52.0 (unable to load class org.bimserver.web.WarServerInitializer)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2498)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4734)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1293)
    at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:672)
    at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:220)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

05-Jan-2016 11:33:02.276 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class org.bimserver.servlets.websockets.jsr356.Jsr356Impl
 java.lang.UnsupportedClassVersionError: org/bimserver/servlets/websockets/jsr356/Jsr356Impl : Unsupported major.minor version 52.0 (unable to load class org.bimserver.servlets.websockets.jsr356.Jsr356Impl)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2498)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4734)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1293)
    at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:672)
    at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:220)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

05-Jan-2016 11:33:02.276 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardContext.listenerStart Skipped installing application listeners due to previous error(s)
...
```

**Comment by berlotti** [comment]
Looks like you are not running the correct JAVA version. 
BIMserver needs JAVA 7.

**Comment by px3l** [comment]
It is JAVA 7

```
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by px3l** [comment]
Issue fixed with latest BIMserver :D
